### ISSUE TITLE
Shot 404 is failing

### ISSUE THREAD

**Issue by ianb** [mozilla-services/screenshots#2749]
If you load a bad shot URL, e.g., `http://localhost:10080/doesnot/exist` then it's giving an error instead of a 404:

```
Error rendering page:
TypeError: Cannot read property 'clipNames' of null

TypeError: Cannot read property 'clipNames' of null
    at /Users/ianbicking/src/pageshot/build/server/pages/shot/server.js:16:13
    at run (/Users/ianbicking/src/pageshot/node_modules/core-js/modules/es6.promise.js:87:22)
    at /Users/ianbicking/src/pageshot/node_modules/core-js/modules/es6.promise.js:100:28
    at flush (/Users/ianbicking/src/pageshot/node_modules/core-js/modules/_microtask.js:18:9)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
```

**Comment by dannycoates** [comment]
Do you know why these lines exist? https://github.com/mozilla-services/screenshots/blob/master/server/src/pages/shot/server.js#L16-L18

**Comment by ianb** [comment]
There was a time when removing the last clip would signal the shot was deleted, when there was incremental editing of the shot.  They aren't needed anymore.
