### ISSUE TITLE
./bin/run-addon should validate the server argument

### ISSUE THREAD

**Issue by 6a68** [mozilla-services/screenshots#2941]
STR:
- clean checkout of screenshots repo (or do `make clean`)
- do `./bin/run-addon -s screenshots.firefox.com`
  - note that the URL does not include the "https://"
- Firefox will start, then immediately crash, with this error:

```
run: WebExtError: installTemporaryAddon: Error: unknownError: Could not install add-on at '/Users/jhirsch/codez/github/mozilla-services-screenshots/addon/webextension': Error: Extension is invalid
    at /Users/jhirsch/codez/github/mozilla-services-screenshots/node_modules/web-ext/dist/webpack:/src/firefox/remote.js:9:5637
    at Client.handleMessage (/Users/jhirsch/codez/github/mozilla-services-screenshots/node_modules/firefox-client/lib/client.js:161:7)
    at Client.readMessage (/Users/jhirsch/codez/github/mozilla-services-screenshots/node_modules/firefox-client/lib/client.js:220:10)
    at Client.onData (/Users/jhirsch/codez/github/mozilla-services-screenshots/node_modules/firefox-client/lib/client.js:186:16)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:554:20)
```

**Comment by ianb** [comment]
This valid could also/instead be validated in `bin/build-scripts/update_manifest.py`
