### ISSUE TITLE
Server build is busted on latest node

### ISSUE THREAD

**Issue by 6a68** [mozilla-services/screenshots#3075]
`./bin/run-server` fails on latest node (8.1.3) fails to uglify the shotindex controller:

```
./bin/build-scripts/bundle_dependencies shotindex build ./build/server/pages/shotindex/controller.js
Building shotindex-bundle.js: deps... bundle... minimizing... Parse error at build/server/static/js/shotindex-bundle.js:3332,8
    let err_msg = 'must be a positive integer or human readable string (e.g. 300
        ^
ERROR: Unexpected token: name (err_msg)
    at JS_Parse_Error.get (eval at <anonymous> (/Users/jhirsch/codez/github/mozilla-services-screenshots/node_modules/uglify-js/tools/node.js:21:1), <anonymous>:86:23)
    at fatal (/Users/jhirsch/codez/github/mozilla-services-screenshots/node_modules/uglify-js/bin/uglifyjs:286:52)
    at run (/Users/jhirsch/codez/github/mozilla-services-screenshots/node_modules/uglify-js/bin/uglifyjs:241:9)
    at Object.<anonymous> (/Users/jhirsch/codez/github/mozilla-services-screenshots/node_modules/uglify-js/bin/uglifyjs:171:5)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)

**Comment by wresuolc** [comment]
This is an issue with the l10n branch

**Comment by ianb** [comment]
This is a problem with code changes in the l10n branch.  Because of some imports in that branch it is now pulling in `server/config.js` and then a bunch of other Node modules.  Our pipeline converts our modules with babel, but doesn't convert modules picked up from node_modules.

It would be nice if our pipeline ran browserify, *then* babel, *then* uglify (instead of babel, browserify, then uglify), but that's just a nice-to-have: we need to fix the imports so these spurious modules aren't being included in the bundles.

**Comment by 6a68** [comment]
This is not a bug in master, just the l10n branch. Closing
