### ISSUE TITLE
dev broken by l10n PR

### ISSUE THREAD

**Issue by 6a68** [mozilla-services/screenshots#3149]
<img width="1034" alt="screen shot 2017-07-19 at 12 17 02 pm" src="https://user-images.githubusercontent.com/96396/28385247-43e0d89a-6c7c-11e7-82ec-fbfc3f122f47.png">

Error text:
Error: TypeError: Cannot read property 'en-US' of undefined
TypeError: Cannot read property 'en-US' of undefined
    at generateMessages (/app/build/server/reactruntime.js:14:30)
    at HeadTemplate.render (/app/build/server/reactruntime.js:36:63)
    at /app/node_modules/react-dom/lib/ReactCompositeComponent.js:796:21
    at measureLifeCyclePerf (/app/node_modules/react-dom/lib/ReactCompositeComponent.js:75:12)
    at ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext (/app/node_modules/react-dom/lib/ReactCompositeComponent.js:795:25)
    at ReactCompositeComponentWrapper._renderValidatedComponent (/app/node_modules/react-dom/lib/ReactCompositeComponent.js:822:32)
    at ReactCompositeComponentWrapper.performInitialMount (/app/node_modules/react-dom/lib/ReactCompositeComponent.js:362:30)
    at ReactCompositeComponentWrapper.mountComponent (/app/node_modules/react-dom/lib/ReactCompositeComponent.js:258:21)
    at Object.mountComponent (/app/node_modules/react-dom/lib/ReactReconciler.js:46:35)
    at ReactCompositeComponentWrapper.performInitialMount (/app/node_modules/react-dom/lib/ReactCompositeComponent.js:371:34)
    at ReactCompositeComponentWrapper.mountComponent (/app/node_modules/react-dom/lib/ReactCompositeComponent.js:258:21)
    at Object.mountComponent (/app/node_modules/react-dom/lib/ReactReconciler.js:46:35)
    at /app/node_modules/react-dom/lib/ReactServerRendering.js:45:36
    at ReactServerRenderingTransaction.perform (/app/node_modules/react-dom/lib/Transaction.js:140:20)
    at renderToStringImpl (/app/node_modules/react-dom/lib/ReactServerRendering.js:43:24)
    at Object.renderToStaticMarkup (/app/node_modules/react-dom/lib/ReactServerRendering.js:83:10)
    at /app/build/server/reactrender.js:42:31

**Comment by 6a68** [comment]
fixed by #3150
