### ISSUE TITLE
add retry to selenium test

### ISSUE THREAD

**Issue by 6a68** [mozilla-services/screenshots#3616]
Might reduce false failure rate

**Comment by ianb** [comment]
If we look at the specific error we're seeing, we might be able to just catch and retry that one. This seems to be the consistent error:

```
  ElementNotInteractableError
      at Object.throwDecodedError (node_modules/selenium-webdriver/lib/error.js:514:15)
      at parseHttpResponse (node_modules/selenium-webdriver/lib/http.js:519:13)
      at doSend.then.response (node_modules/selenium-webdriver/lib/http.js:441:30)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)
  From: Task: WebElement.click()
      at Driver.schedule (node_modules/selenium-webdriver/lib/webdriver.js:807:17)
      at WebElement.schedule_ (node_modules/selenium-webdriver/lib/webdriver.js:2010:25)
      at WebElement.click (node_modules/selenium-webdriver/lib/webdriver.js:2092:17)
      at expectCreatedShot (test/test.js:267:20)
      at driver.getAllWindowHandles.then (test/test.js:175:12)
      at ManagedPromise.invokeCallback_ (node_modules/selenium-webdriver/lib/promise.js:1376:14)
      at TaskQueue.execute_ (node_modules/selenium-webdriver/lib/promise.js:3084:14)
      at TaskQueue.executeNext_ (node_modules/selenium-webdriver/lib/promise.js:3067:27)
      at asyncRun (node_modules/selenium-webdriver/lib/promise.js:2927:27)
      at node_modules/selenium-webdriver/lib/promise.js:668:7
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)
```

I think we could wrap `saveButton.click();` with a retry that catches this specific exception. Except with promises and callbacks.

**Comment by 6a68** [comment]
Selenium failures often are actually caused by a prior step going sideways. I bet retrying the whole test would work more reliably. We could also ping dave hunt and the webqa people to get advice on debugging the test.

**Comment by ianb** [comment]
I think the error is actually somewhere in here:

```js
    }).then(() => {
      return driver.wait(
        until.elementLocated(By.css(".preview-button-save"))
      );
    }).then((saveButton) => {
      return expectCreatedShot(driver, () => {
          saveButton.click();
     });
    });
```

Specifically between `until.elementLocated(By.css(".preview-button-save"))` and `saveButton.click();` the button must go away or otherwise be unavailable. There's not much code that runs between those two... but maybe I can include `until.elementLocated(By.css(".preview-button-save"))` in the retry and see if it helps.
